### ISSUE TITLE
Move events page to new site

### ISSUE THREAD

**Issue by richyvk** [LibraryCarpentry/lc-second-website#1]
Link to events on the new site links to this page on the old site: http://librarycarpentry.github.io/workshops/

A new page on the new site needs to be written, and content moved to that.

May be possible to use the blog page as a template, but perhaps a new template should be written and used. 

Ideally you should be able to add new events as markdown.

**Comment by jezcope** [comment]
> Ideally you should be able to add new events as markdown.

Have you got any thoughts about what you'd like this to look like? The current page stores machine-readable data in YAML and has a template that generates HTML from that. It feels neat to me (separation of content & presentation) but people do find it rather tricky to figure out how to add events. One alternative could be one Markdown file per event with some structured metadata, which is how blog posts are currently done.

Longer term, I guess the solution is to tie this into [AMY](https://github.com/swcarpentry/amy), as is done with Software/Data Carpentry. @gvwilson @weaverbel?

**Comment by gvwilson** [comment]
This can be done with [Jekyll Collections](https://jekyllrb.com/docs/collections/):

1. Add an entry to `_config.yml` to create an `events` collection.
2. Have people create a file `_events/yyyy-mm-dd-location.md` for each event.
3. Create a page that loops over the entries in `_events` to create a page displaying information about all of them.

It's easy to set up, but honestly, I think we should go straight to AMY: we're going to wind up there anyway.

**Comment by jezcope** [comment]
:+1: to AMY. What needs to be done?

**Comment by gvwilson** [comment]
@weaverbel, over to you to close the loop with the Carpentries?

**Comment by weaverbel** [comment]
The issue at the moment is that while workshops are stored in AMY, they don't appear on any workshops page as far as I know and I don't know how to pull out a list from AMY either. I will talk to someone in the Carpentries and see what I can find out about how we can render workshop listings on our site from there.

**Comment by jezcope** [comment]
Looks like there's a data file at `_data/amy.yml` in both [SWC](https://github.com/swcarpentry/website/blob/gh-pages/_data/amy.yml) and [DC website](https://github.com/datacarpentry/datacarpentry.github.io/blob/master/_data/amy.yml) repositories. They seem to be used differently though, because the DC one was updated approx half an hour ago while the SWC one dates back to 2016. I'm guessing that there's somewhere else that the SWC website is deployed from while the DC one just uses GH pages?

**Comment by weaverbel** [comment]
I have got upcoming workshops on `What We Do` page and past workshops on `About`.
Not perfect ! But we should soon have workshops listings via AMY so it will be OK till then.
