### ISSUE TITLE
Embed Twitter timeline on blog page

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-second-website#14]
I would like to embed the Library Carpentry Twitter timeline on the blog page. Does anyone know how to do that? https://github.com/LibraryCarpentry/new-website/blob/gh-pages/blog.html

Code is:
`<a class="twitter-timeline" href="https://twitter.com/LibCarpentry?ref_src=twsrc%5Etfw">Tweets by LibCarpentry</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> `

**Comment by weaverbel** [comment]
@richyvk or @libcce do you know how to do this? I managed to embed it but it looked awful and wasn't nice. Aiming for something like the way it looks on this page: https://carpentries.org/blog/

**Comment by evanwill** [comment]
PR #19 addresses this, 
just modeled on https://carpentries.org/blog/ style

put the blog roll into a `col-md-7` with twitter feed in `col-md-3`, in a container with an `col-md-offset-1` to maintain the basic text block look of the other pages.

**Comment by weaverbel** [comment]
Awesome @evanwill - thanks !
