### ISSUE TITLE
Broken links in the list of past workshops

### ISSUE THREAD

**Issue by olexandr-konovalov** [LibraryCarpentry/lc-second-website#21]
At about -> past workshops, events where there is no website available, are just linked to http://librarycarpentry.org/ - perhaps better to have no hyperlink at all?

As an additional remark, I miss the map of past workshops - it is very informative and very useful for making presentations.

**Comment by libcce** [comment]
Does the new website address some of your issues https://librarycarpentry.org/upcoming_workshops/ ? Repo at https://github.com/LibraryCarpentry/librarycarpentry.github.io

**Comment by olexandr-konovalov** [comment]
Thanks - migrated this to https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/1
