### ISSUE TITLE
About, past workshops

### ISSUE THREAD

**Issue by uom-nilani** [LibraryCarpentry/lc-second-website#22]
This list should include only the library carpentry workshops, not data or software carpentry workshops. E.g. 2017 workshop in Manchester

**Comment by libcce** [comment]
Does this page respond to this issue https://librarycarpentry.org/upcoming_workshops/ ?

**Comment by libcce** [comment]
Closing this issue. Please add to this issue https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/1 if there is anything else needed.
