### ISSUE TITLE
Lesson development status

### ISSUE THREAD

**Issue by olexandr-konovalov** [LibraryCarpentry/lc-second-website#23]
In "Lesson dev" there are stable, beta and alpha lessons, but it is not specified which lesson has which status.

**Comment by olexandr-konovalov** [comment]
See also #15 about lesson descriptions.

**Comment by libcce** [comment]
Does this page respond to this issue https://librarycarpentry.org/lessons/ ?

**Comment by olexandr-konovalov** [comment]
Think so, thanks!
