### ISSUE TITLE
Contact page - Request one link

### ISSUE THREAD

**Issue by uom-nilani** [LibraryCarpentry/lc-second-website#25]
Point 4 - want a library carpentry workshop at you institution - request one link goes to the page https://software-carpentry.org/workshops/request/ which is very confusing as refers to software and data carpentries

**Comment by olexandr-konovalov** [comment]
Moreover, that linked page does not mention Library Carpentry at all...

**Comment by uom-nilani** [comment]
Same link appears in 'what we do' / 'workshops'

**Comment by uom-nilani** [comment]
Same link appears in 'what we do' / 'workshops'

**Comment by libcce** [comment]
This information has been updated https://librarycarpentry.org/workshops/ and in other locations but please submit an issue here https://github.com/LibraryCarpentry/librarycarpentry.github.io if you think anything is missing. Thanks!!!
