### ISSUE TITLE
Broken link in "Terms of Use"

### ISSUE THREAD

**Issue by olexandr-konovalov** [LibraryCarpentry/lc-second-website#27]
Broken link in "Terms of Use" at the bottom of the page - it just returns to the top of the page.

**Comment by libcce** [comment]
Is this corrected in the new site https://librarycarpentry.org/ ?

**Comment by olexandr-konovalov** [comment]
Looks so, thanks! Can't see "Terms of Use" there, but all links seem to work!

**Comment by libcce** [comment]
Since we are using the Carpentries-based template, the Carpentries privacy policy is listed.
