### ISSUE TITLE
Onboarding existing SWC + DC instructors to teach LC

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-second-website#6]
We need to cover:

- Different demographic - librarians not researchers - motivations for attending are very different
- Dual outcomes - 1) improving own practices 2) teach skills to others
- Issue when people are 'drafted' to attend - overcoming resistance and reluctance of some attendees
- Library roles - general background on types of library, types of role
- Practical applications for the skills - how will they use them and apply them?
- Workarounds for people who have no laptop/no ability to install software

**Comment by jt14den** [comment]
* How about we work on something like this for library carpentry: https://software-carpentry.org/audience/
* Some poss. profiles: 
   * Metadata person working with bibliographic reports or metadata transformations
   * Librarians who work with researchers - working with data, scholarly comm 
   * Public library librarians, computational skills, cyber security

**Comment by weaverbel** [comment]
I would also add these @jt14den 
- national and state library staff - people working with digital collections + exhibitions
- repository staff working with structured collections
- library systems staff working with bespoke or in-house developed systems

**Comment by pitviper6** [comment]
Corporate/finance librarian
Library admins 
Media/makerspace librarian
Acquisitions librarian/working with publisher and budget data

**Comment by jezcope** [comment]
We have local finance & HR professionals to supplement our university central finance & HR. They aren't considered "librarians" per se but certainly have a use for these skills. Is this what you mean by corporate/finance librarian/library admins @pitviper6?

**Comment by pitviper6** [comment]
Yes, by 'library admins.'

For corporate/finance librarians, I'm thinking of business librarians in academia, corporate librarians at financial or law firms who deal with a ton of data they need to analyze for reports. When I was an insurance librarian, I used to munge huge datasets of demographics and annual/financial report data, and hoo boy I could've used some OpenRefine. 

Also, every university has a set of prospect researchers in their gifts/endowment departments, almost all of whom were former business librarians and who keep massive amounts of data, both text-based and financial, on prospects and need to generate reports out of them.

**Comment by goldmj** [comment]
@cmbz Do you think the profiles you have gathered would be helpful here? We discussed this at a recent SWC Instructor Training.

**Comment by libcce** [comment]
New audience page https://librarycarpentry.org/audience/ speaks to this issue. If not, please create a new issue here https://github.com/LibraryCarpentry/librarycarpentry.github.io
