### ISSUE TITLE
Git or GitHub logo?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-second-website#8]
The [portfolio "Git" logo](https://github.com/LibraryCarpentry/new-website/tree/gh-pages/img/portfolio) is actually [GitHub's Octocat](https://github.com/logos). Is that intended for cuteness, at the expense of accuracy?

If not, how about aligning it? Either that logo with "GitHub" or ["Git" and its logo](https://git-scm.com/downloads/logos).

**Comment by jezcope** [comment]
@katrinleinweber That's a good point. I do quite like the Git logo.

**Comment by richyvk** [comment]
I can sort that out - will switch over to git logo.

**Comment by weaverbel** [comment]
Done
